#!/usr/bin/env bash

if [[ $# -ne 1 ]]
then
  echo 'usage: <version>'
  exit 1
fi

cp Cargo.toml Cargo.toml.bak
sed -Ee 's/^version = ".*"/version = "'"$1"'"/' Cargo.toml.bak > Cargo.toml

cargo deb

mv Cargo.toml.bak Cargo.toml
