#!/usr/bin/env bash

if [[ $# -ne 1 ]]
then
  echo 'usage: <version>'
  exit 1
fi

cp Cargo.toml Cargo.toml.bak
sed -Ee 's/^version = ".*"/version = "'"$1"'"/' Cargo.toml.bak > Cargo.toml

./bin/ronn -r5 man/*.ronn

cargo deb

mv Cargo.toml.bak Cargo.toml
